Started logging messages at Sat Aug 30 06:54:58 2014
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 31 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 89
Info:            Created 
Info:        Working on 90
Info:            Created 
Info:        Working on 136
Info:            Created 
Info:        Working on 140
Info:            Created 
Info:        Working on 8
Info:            Created 
Info:        Working on 127
Info:            Created 
Info:        Working on 201
Info:            Created 
Info:        Working on 202
Info:            Created 
Info:        Working on 286
Info:            Created 
Info:        Working on 187
Info:            Created 
Info:        Working on 13
Info:            Created 
Info:        Working on 186
Info:            Created 
Info:        Working on 268
Info:            Created 
Info:        Working on 19
Info:            Created 
Info:        Working on 263
Info:            Created 
Info:        Working on 362
Info:            Created 
Info:        Working on 31
Info:            Created 
Info:        Working on 452
Info:            Created 
Info:        Working on 53
Info:            Created 
Info:        Working on 370
Info:            Created 
Info:        Working on 379
Info:            Created 
Info:        Working on 96
Info:            Created 
Info:        Working on 480
Info:            Created 
Info:        Working on 481
Info:            Created 
Info:        Working on 516
Info:            Created 
Info:        Working on 544
Info:            Created 
Info:        Working on 471
Info:            Created 
Info:        Working on 312
Info:            Created 
Info:        Working on 306
Info:            Created 
Info:        Working on 466
Info:            Created 
Info:        Working on 541
Info:            Created 
Info:        Working on 597
Info:            Created 
Info:        Working on 636
Info:            Created 
Info:        Working on 664
Info:            Created 
Info:        Working on 672
Info:            Created 
Info:        Working on 658
Info:            Created 
Info:        Working on 587
Info:            Created 
Info:        Working on 586
Info:            Created 
Info:        Working on 598
Info:            Created 
Info:        Working on 548
Info:            Created 
Info:        Working on 163
Info:            Created 
Info:        Working on 204
Info:            Created 
Info:        Working on 292
Info:            Created 
Info:        Working on 377
Info:            Created 
Info:        Working on 280
Info:            Created 
Info:        Working on 351
Info:            Created 
Info:        Working on 350
Info:            Created 
Info:        Working on 373
Info:            Created 
Info:        Working on 405
Info:            Created 
Info:        Working on 458
Info:            Created 
Info:        Working on 321
Info:            Created 
Info:        Working on 487
Info:            Created 
Info:        Working on 231
Info:            Created 
Info:        Working on 409
Info:            Created 
Info:        Working on 223
Info:            Created 
Info:        Working on 434
Info:            Created 
Info:        Working on 510
Info:            Created 
Info:        Working on 568
Info:            Created 
Info:        Working on 614
Info:            Created 
Info:        Working on 622
Info:            Created 
Info:        Working on 665
Info:            Created 
Info:        Working on 644
Info:            Created 
Info:        Working on 608
Info:            Created 
Info:        Working on 559
Info:            Created 
Info:        Working on 498
Info:            Created 
Info:        Working on 420
Info:            Created 
Info:        Working on 332
Info:            Created 
Info:        Working on 240
Info:            Created 
Info:        Working on 159
Info:            Created 
Info:        Working on 256
Info:            Created 
Info:        Working on 355
Info:            Created 
Info:        Working on 444
Info:            Created 
Info:        Working on 518
Info:            Created 
Info:        Working on 515
Info:            Created 
Info:        Working on 573
Info:            Created 
Info:        Working on 619
Info:            Created 
Info:        Working on 651
Info:            Created 
Info:        Working on 669
Info:            Created 
Info:        Working on 654
Info:            Created 
Info:        Working on 216
Info:            Created 
Info:        Working on 309
Info:            Created 
Info:        Working on 402
Info:            Created 
Info:        Working on 483
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 6.205e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Sat Aug 30 06:54:58 2014
